pipeline {
    agent any

    stages {
        stage('Unit Tests - Backend') {
            agent {
                docker {
                    image 'snakee/golang-junit:1.21'
                    reuseNode true
                }
            }
            environment {
                GOCACHE = "${WORKSPACE}/.cache/go-build"
                GOPATH = "${WORKSPACE}/.go"
                HOME = "${WORKSPACE}"  // This tells Go to use workspace as home
            }
            steps {
                dir('bugtracker-backend') {
                    sh 'go test -v ./...'
                }
            }
        }

        stage('Unit Tests - Frontend') {
            agent {
                docker {
                    image 'node:20-alpine'
                    reuseNode true
                }
            }
            steps {
                dir('bugtracker-frontend') {
                    sh '''
                    npm ci
                    npm test
                    '''
                }
            }
        }
    }
}